### ISSUE TITLE
Segmentation fault on processing exit 

### ISSUE THREAD

**Issue by jyha200** [poseidonos/poseidonos#1]
Hello.

I just executed bin/ibofos, scanned device and then exited.
But the ibofos process is killed with seg. fault.

I attached screen shot.

![image](https://user-images.githubusercontent.com/82130430/113959186-62afc900-985d-11eb-85eb-0d816f7228ef.png)

**Comment by hjin-so** [comment]
good

**Comment by QueOh** [comment]
Hi.
Thank you for the report.
It is hard to know where the problem occurred based on what was given.

Please upload configuration file, log file, and system information(CPU, memory, and storage device).

**Comment by jyha200** [comment]
There is no nvme sotrage device.
The results of 'lsblk', 'lscpu', 'lsmem' command are as below.
![image](https://user-images.githubusercontent.com/82130430/113966578-4b2b0d00-986a-11eb-8161-de768266ad15.png)
![image](https://user-images.githubusercontent.com/82130430/113966649-71e94380-986a-11eb-95ee-18ebf78c7191.png)
![image](https://user-images.githubusercontent.com/82130430/113966717-9513f300-986a-11eb-8ec2-8926e9080682.png)

I have no config file used, and attached ibofos.log.
[ibofos.log](https://github.com/poseidonos/poseidonos/files/6275907/ibofos.log)

**Comment by hsung-yang** [comment]
Hi, the issue that you reported is resolved and merged into main branch

**Comment by Wonchul08Lee** [comment]
Patch merged at ae8c128f6380beeded5435fa6ce3b09e28dbde48. . 
Thanks @jyha200!

**Comment by Wonchul08Lee** [comment]
This is fixed and running normally.
