### ISSUE TITLE
POS Management Tool

### ISSUE THREAD

**Issue by jhyunleehi** [poseidonos/poseidonos#12]
I want to install Management Tool to use "learning_pos_management_tool.md"
but I  cannot find this file $POS_MGMT_HOME /m9k/install_all.sh

**Comment by mjlee34** [comment]
Hi, Management Tool has not been currently released. It is expected to be released in around October.

**Comment by jhyunleehi** [comment]
@mjlee34 
hi, I want to test the REST API to see if it can work with our Storage Management System. In particular, I want to test the REST API integration.

**Comment by mjlee34** [comment]
Unfortunately, REST API is supported via Management Tool, which will be released in October. Thanks.

**Comment by KyuhoSon** [comment]
Hi.
If your issule solved, can I close this issue?
