### ISSUE TITLE
If GO is already installed no need to download go and Install 

### ISSUE THREAD

**Issue by thkrishn** [poseidonos/poseidonos#15]
pkgdep.sh tries to install GO even if go14 or a new version is available 

this script needs to check if its installed if not only then install GO
pkgdep.sh

```
#!/bin/sh
# Please run this script as root.

SYSTEM=`uname -s`
POS_ROOT=$(readlink -f $(dirname $0))/..

${POS_ROOT}/script/install_go.sh
```

**Comment by mjlee34** [comment]
@thkrishn , we've found that the issue occurs for the following reasons:

1. POS is assuming that GO is installed in a default directory (/usr/local/go). 
2. POS does not check if a newer verison of GO (> go1.14.4) is already installed. 

These need to be addressed.

**Comment by KyuhoSon** [comment]
Hi.
If your issule solved, can I close this issue?
