### ISSUE TITLE
build_ibofos make fails

### ISSUE THREAD

**Issue by aagi-girish** [poseidonos/poseidonos#24]
Hi,
We tried to build the Poseidon OS and it shows the make error as below. We tested the version of cmake and the results are uploaded below. Please suggest your ideas. 
![Screenshot from 2021-11-05 14-23-00](https://user-images.githubusercontent.com/80010347/140453439-78af3481-0536-4906-9145-9a04aad6b4ef.png)

![Screenshot from 2021-11-05 14-26-14](https://user-images.githubusercontent.com/80010347/140453419-b9bf6907-50a7-4370-80d7-349fe94cfd32.png)
)

**Comment by KyuhoSon** [comment]
Hi.
Can you tell me which command did you use to build the Poseidon OS?

**Comment by aagi-girish** [comment]
We used the below command:

cd script/
sudo ./build_ibofos.sh

**Comment by KyuhoSon** [comment]
Can you tell me which OS do you use?

**Comment by aagi-girish** [comment]
We use UBUNTU 18.04

**Comment by KyuhoSon** [comment]
It seems like it failed to build lib/spdk, thus building poseidonos failed. 
Can you run below command, and attach it to here?

cd lib
sudo make spdk

**Comment by aagi-girish** [comment]
make spdk failed. attached the result.
[spdk.txt](https://github.com/poseidonos/poseidonos/files/7493332/spdk.txt)

**Comment by aagi-girish** [comment]
We performed sudo git config --global user.name and email. After that make SPDK shows a different error. attached the latest output.
[spdk-new.txt](https://github.com/poseidonos/poseidonos/files/7493375/spdk-new.txt)

**Comment by KyuhoSon** [comment]
It looks like patch is not applied. 
Can you try the below command?

cd lib/spdk
sudo patch -t -p0 -i ../spdk-21.04.patch
cd ../
sudo make spdk

**Comment by aagi-girish** [comment]
Tried patching but spdk make still fails. Attached the output.
[patching.txt](https://github.com/poseidonos/poseidonos/files/7493642/patching.txt)
[spdk_after_patching.txt](https://github.com/poseidonos/poseidonos/files/7493643/spdk_after_patching.txt)

**Comment by KyuhoSon** [comment]
Build cache would remain in lib/spdk-prefix. Can you remove lib/spdk-prefix with command below and run build script?
cd lib
sudo rm -r spdk-prefix

Also, due to the same reason, other library build would make some error. Then, please reset all files in lib directory, and run build script.

cd lib
sudo rm -rf *
git checkout -- .
sudo ./build_lib.sh

**Comment by aagi-girish** [comment]
Hi,

We tried the above commands and found the spdk lost its sync with git repository. We hope a fresh git pull can help. Please share your thoughts on the below attached log.
[spdk-error.txt](https://github.com/poseidonos/poseidonos/files/7502319/spdk-error.txt)

**Comment by KyuhoSon** [comment]
Hi, 

Sorry for your inconvinience, but I agree that fresh git pull would help. As it failed in the middle of library build, some build caches might remain, and that makes library build hard.

**Comment by aagi-girish** [comment]
Thank you for the help,
The fresh git pull worked with ease. Closing the issue. 

![image](https://user-images.githubusercontent.com/80010347/141012670-9c603c45-4e73-44e1-90d1-18454cb38944.png)
