### ISSUE TITLE
RAID options

### ISSUE THREAD

**Issue by aagi-girish** [poseidonos/poseidonos#26]
Hi Team,

Keen to know if the PoseidonOS supports RAID 0 or just a Logical volume of disks instead of RAID 5?

For fault-tolerance/redundancy, can we use multiple servers and replicate the data across them?
 
Thanks.

**Comment by hsung-yang** [comment]
Hi @aagi-girish ,
Thank you for your interest in POS.
We have already considered the functions you mentioned (RAID0 and fault-tolerance using other server)
and It will be distributed in the second half of next year after implementation in the first half.

**Comment by aagi-girish** [comment]
That's great @hsung-yang.
