### ISSUE TITLE
Compilation -- Offline Compilation support 

### ISSUE THREAD

**Issue by thkrishn** [poseidonos/poseidonos#29]
I am using the v0.10.6 branch and I am unable to build the software on an environment which has no internet access 
I am seeing this issues 

```
/home/thkrishn/poseidonos/tool/cli/script/build_cli.sh
go: code.cloudfoundry.org/bytefmt@v0.0.0-20210608160410-67692ebc98de: Get "https://proxy.golang.org/code.cloudfoundry.org/bytefmt/@v/v0.0.0-20210608160410-67692ebc98de.mod": dial tcp 172.217.164.113:443: i/o timeout
mv: cannot stat './cli': No such file or directory
go: code.cloudfoundry.org/bytefmt@v0.0.0-20210608160410-67692ebc98de: Get "https://proxy.golang.org/code.cloudfoundry.org/bytefmt/@v/v0.0.0-20210608160410-67692ebc98de.mod": dial tcp 172.217.164.113:443: i/o timeout
go: code.cloudfoundry.org/bytefmt@v0.0.0-20210608160410-67692ebc98de: Get "https://proxy.golang.org/code.cloudfoundry.org/bytefmt/@v/v0.0.0-20210608160410-67692ebc98de.mod": dial tcp 172.217.164.113:443: i/o timeout

``` 

Is there a workaround for this?
I am using Ubuntu 20.04

**Comment by minjoon-ahn** [comment]
Hi, thkrishn
We are already offering '-i' option for the additional build.
use like this : ./script/build_ibofos.sh -i
I hope the answer will be helpful

**Comment by so931** [comment]
Hi, thikrishn.
Above answer is a mistake.
At this time, there is no way to build Poseidonos without internet access.
But soon plan to provide a pre-built docker image and vagrantfile for this.
Please wait to next release.

**Comment by QueOh** [comment]
Hi, thkishn.
PoseidonOS only support Ubuntu 18.04 now.
