### ISSUE TITLE
the core file name is hard to access

### ISSUE THREAD

**Issue by thkrishn** [poseidonos/poseidonos#30]
The core file is in the name "'!opt!poseidonos!bin!poseidonos.core'"

if the ! can be fixed we dont need to escape the strings to access it

I am using version 10.6

**Comment by sejun000** [comment]
Hello,  Thkrishn

Thanks for commenting your opinions. 
Actually, we use core pattern "/etc/pos/core/%E.core" as default, to indicates full path of the core file. 
%E option automatically uses "!" string to indicates the path of its executable file.
However if you want to change the core file name in your code, please fix as below.
And we also plan to configure this file name and core's detailed options through config file in the next release.(/etc/pos/pos.conf).

diff --git a/src/main/poseidonos.cpp b/src/main/poseidonos.cpp
index 8e577e6d..c2f80846 100644
--- a/src/main/poseidonos.cpp
+++ b/src/main/poseidonos.cpp
@@ -196,7 +196,7 @@ Poseidonos::_InitDebugInfo(void)
         POS_TRACE_DEBUG(POS_EVENT_ID::DEBUG_CORE_DUMP_SETTING_FAILED, "Core directory will not be created");
         return;
     }
-    ret = system("echo /etc/pos/core/%E.core > /proc/sys/kernel/core_pattern");
+    ret = system("echo AsYouWant > /proc/sys/kernel/core_pattern");
     if (ret != 0)
     {
         POS_TRACE_DEBUG(POS_EVENT_ID::DEBUG_CORE_DUMP_SETTING_FAILED, "Core pattern is not set properly");
