### ISSUE TITLE
build_ibofos.sh failed

### ISSUE THREAD

**Issue by qiaobaaa** [poseidonos/poseidonos#32]
hello，When I run sudo ./build_ibofos.sh some errors occur. Please suggest your ideas
Error message：
Compiling [allocator.cpp]...
/usr/local/go/bin/go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
go: github.com/golang/protobuf@v1.5.2: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.mod": dial tcp: lookup proxy.golang.org: no such host
Makefile:17: recipe for target 'protobuf' failed
make[1]: *** [protobuf] Error 1
Makefile:235: recipe for target 'pos-exporter' failed
make: *** [pos-exporter] Error 2
make: *** Waiting for unfinished jobs....

/home/sivp/pos/poseidonos/tool/cli/script/build_cli.sh
go: code.cloudfoundry.org/bytefmt@v0.0.0-20210608160410-67692ebc98de: Get "https://proxy.golang.org/code.cloudfoundry.org/bytefmt/@v/v0.0.0-20210608160410-67692ebc98de.mod": dial tcp: lookup proxy.golang.org: no such host
mv: cannot stat './cli': No such file or directory
go: code.cloudfoundry.org/bytefmt@v0.0.0-20210608160410-67692ebc98de: Get "https://proxy.golang.org/code.cloudfoundry.org/bytefmt/@v/v0.0.0-20210608160410-67692ebc98de.mod": dial tcp: lookup proxy.golang.org: no such host
go: code.cloudfoundry.org/bytefmt@v0.0.0-20210608160410-67692ebc98de: Get "https://proxy.golang.org/code.cloudfoundry.org/bytefmt/@v/v0.0.0-20210608160410-67692ebc98de.mod": dial tcp: lookup proxy.golang.org: no such host
chmod: cannot access '../bin/gen_md': No such file or directory
chmod: cannot access '../bin/gen_man': No such file or directory

**Comment by minjoon-ahn** [comment]
Hi, qiaobaaa,
Access to some sites seems to be restricted in your environment. If you are located on a private network, please contact the network administrator to check access to the site.

**Comment by qiaobaaa** [comment]
Thank you very much the problem has been solved
