### ISSUE TITLE
losing NVMe drives after executing ./start_poseidonos.sh

### ISSUE THREAD

**Issue by neteng1** [poseidonos/poseidonos#490]
I am still trying to bring up a virtual environment for evaluation. I now can get the application to run. However, I do not see al the NVMe drives. Any help would be greatly appreciated. Here is what I start with:

kouellette@oe-poseidon:~$ lsblk
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0                         2:0    1  1.4M  0 disk 
sda                         8:0    0   20G  0 disk 
├─sda1                      8:1    0    1M  0 part 
├─sda2                      8:2    0    1G  0 part /boot
└─sda3                      8:3    0   19G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0   19G  0 lvm  /
sr0                        11:0    1 68.1M  0 rom  
sr1                        11:1    1  969M  0 rom  
nvme0n1                   259:0    0   20G  0 disk 
nvme0n2                   259:1    0   20G  0 disk 
nvme0n3                   259:2    0   20G  0 disk 
kouellette@oe-poseidon:~$ 

After I start poseidonos using ./start_poseidonos.sh I no longer see them here.

kouellette@oe-poseidon:~/workspace/ibofos/poseidonos$ lsblk
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0                         2:0    1  1.4M  0 disk 
sda                         8:0    0   20G  0 disk 
├─sda1                      8:1    0    1M  0 part 
├─sda2                      8:2    0    1G  0 part /boot
└─sda3                      8:3    0   19G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0   19G  0 lvm  /
sr0                        11:0    1 68.1M  0 rom  
sr1                        11:1    1  969M  0 rom  
kouellette@oe-poseidon:~/workspace/ibofos/poseidonos$ 

I then scan to see if maybe Poseidonos sees them and I get the following:

kouellette@oe-poseidon:~/workspace/ibofos/poseidonos$ sudo ./bin/poseidonos-cli device scan
kouellette@oe-poseidon:~/workspace/ibofos/poseidonos$ sudo ./bin/poseidonos-cli device list --unit
Name           |SerialNumber        |Address        |Class         |ModelNumber                |NUMA   |Size
-------------- |------------------- |-------------- |------------- |-------------------------- |------ |------------------
unvme-ns-0     |VMware NVME_0000    |0000:03:00.0   |SYSTEM        |VMware Virtual NVMe Disk   |0      |20G

Should I not see all three at this point? 

I attached the pos.log and syslog files. The time to look for is around 10-21-2022 14:41 

[syslog.log](https://github.com/poseidonos/poseidonos/files/9840450/syslog.log)
[pos.log](https://github.com/poseidonos/poseidonos/files/9840410/pos.log)

**Comment by syeonshin** [comment]
hi neteng1 , 
It seems each device has the same serial number. Please try again with different Serial Number :)

pos.log 

`DEVICEMGR_CHK_DUPLICATE - NONE (cause: NONE, solution: NONE, variables: DEVICE DUPLICATED Name:unvme-ns-1, SN: VMware NVME_0000)

DEVICEMGR_CHK_DUPLICATE - NONE (cause: NONE, solution: NONE, variables: DEVICE DUPLICATED Name:unvme-ns-2, SN: VMware NVME_0000)`

**Comment by neteng1** [comment]
I guess I missed that when I saw DEVICEMGR_CHK_DUPLICATE - **NONE**.  Interesting is the lsblk command led me to believe they were individual disks. 

kouellette@oe-poseidon:~$ lsblk
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0                         2:0    1  1.4M  0 disk 
sda                         8:0    0   20G  0 disk 
├─sda1                      8:1    0    1M  0 part 
├─sda2                      8:2    0    1G  0 part /boot
└─sda3                      8:3    0   19G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0   19G  0 lvm  /
sr0                        11:0    1 68.1M  0 rom  
sr1                        11:1    1  969M  0 rom  
nvme0n1                   259:0    0   20G  0 disk 
nvme0n2                   259:1    0   20G  0 disk 
nvme0n3                   259:2    0   20G  0 disk 

But looking for the serial number via lshw it shows them as partitions so one serial number. 

*-storage
                description: Non-Volatile memory controller
                product: VMware
                vendor: VMware
                physical id: 0
                bus info: pci@0000:03:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: storage nvm_express bus_master cap_list rom
                configuration: driver=nvme latency=0 maxlatency=255 mingnt=6
                resources: irq:18 memory:fd4fc000-fd4fffff ioport:4000(size=8) memory:fd400000-fd401fff
              *-nvme0
                   description: NVMe device
                   product: VMware Virtual NVMe Disk
                   physical id: 0
                   logical name: /dev/nvme0
                   version: 1.3
                   serial: VMware NVME_0000
                   configuration: nqn=nqn.2014-08.org.nvmexpress:uuid:521c404f-e032-b26e-479a-349986f6ffff state=live
                 *-namespace:0
                      description: NVMe namespace
                      physical id: 1
                      logical name: /dev/nvme0n1
                 *-namespace:1
                      description: NVMe namespace
                      physical id: 2
                      logical name: /dev/nvme0n2
                 *-namespace:2
                      description: NVMe namespace
                      physical id: 3
                      logical name: /dev/nvme0n3


I will look to see if I can correct that in VMWare's Fusion configurations. 

Thank you for pointing that out.
