### ISSUE TITLE
Poseidon does not start. 

### ISSUE THREAD

**Issue by neteng1** [poseidonos/poseidonos#552]
I am back trying to get an evaluation up and running as I am no longer trying to emulate the NVMe drives. I was able to download the code and build it. But when I try to start the application using the "sudo ./start_poseidonos.sh" script, I get the following output:
--------------------------------------------------------------
keith@poseidonos:~/dev/ibofos/poseidonos/script$ sudo ./start_poseidonos.sh 
[sudo] password for keith: 
0000:0b:00.0 (144d a808): Already using the nvme driver
0000:1b:00.0 (1987 5013): Already using the nvme driver
0000:13:00.0 (1179 0113): Already using the nvme driver
Setting maximum # of Huge Page Size is 2/3 of Total Memory Size
0000:13:00.0 (1179 0113): nvme -> uio_pci_generic
0000:0b:00.0 (144d a808): nvme -> uio_pci_generic
0000:1b:00.0 (1987 5013): nvme -> uio_pci_generic
/home/keith/dev/ibofos/poseidonos/script
apport.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apport
Current maximum # of memory map areas per process is 65530.
Setting maximum # of memory map areas per process to 65535.
vm.max_map_count = 65535
Setup env. done!
Execute poseidonos
Error: Could not connect to the CLI server. Is PoseidonOS running? (internal error message: context deadline exceeded)
Usage:
  poseidonos-cli system info [flags]

Flags:
  -h, --help   help for info

Global Flags:
      --debug            Print response for debug.
      --fs string        Field separator for the output. (default "|")
      --ip string        Set IPv4 address to PoseidonOS for this command. (default "127.0.0.1")
      --json-req         Print request in JSON form.
      --json-res         Print response in JSON form.
      --node string      Name of the node to send this command. When both --ip and this flag are specified, this flag is applied only.
      --port string      Set the port number to PoseidonOS for this command. (default "18716")
      --timeout uint32   Timeout for this command in seconds. (Note: array unmount command has 30 minutes timeout.) (default 180)
      --unit             Display unit (B, KB, MB, ...) when displaying capacity.

./start_poseidonos.sh: line 42: 2: command not found
Wait poseidonos for 1 seconds
----------------------------------------------------------------
[pos.log](https://github.com/poseidonos/poseidonos/files/9974388/pos.log)

[pos_major.log](https://github.com/poseidonos/poseidonos/files/9974391/pos_major.log)

[syslog.log](https://github.com/poseidonos/poseidonos/files/9974393/syslog.log)

I attached logs for review. In the pos.log and pos_major.log, I only have the entries for the time I attempted to start the application. Syslog I provided the whole thing in case there is something obscure in there.  I do not see any "errors" in the pos.log. I am at a little bit at a loss of what next to look at. Any help would be greatly appreciated.

**Comment by minjoon-ahn** [comment]
Hi neteng1,

Thank you for your valuable report.

1. Please perform the environment check as below and paste the results displayed on the console.
cd ibofos/tool/resourceChecker/
./make_environment_checker_so_file.sh
./environment_check_so.py

2. Please upload /etc/pos/pos.conf file also.

**Comment by neteng1** [comment]
Thank you minjoon-ahn for you quick response. Here are the items you request:

1. keith@poseidonos:~/dev/ibofos/poseidonos/tool/resourceChecker$ ./make_environment_checker_so_file.sh 
keith@poseidonos:~/dev/ibofos/poseidonos/tool/resourceChecker$ ./environment_check_so.py 
sh: 1: make_environment_checker_so_file.sh: not found
#1
1. OS :  Matched with host OS version
2. Kernel :  Matched with host Kernel version
3-1 number of cpu : 12
3-2 clock of cpu : 2699 MHz 
4-1 Total mem info : 32111 MB
4-2 available mem info : 30450 MB
5. number of pcie device : 3
6. Check RAID configuration
------------------------------
RAID Type      |  Support
------------------------------
RAID0          |  Available
RAID10         |  Available
RAID5          |  Available
------------------------------
Meet minimum cpu numebr
Meet minimum memory
99-custom-nvme.rules File existed

2. /etc/pos/pos.conf file is here.

[pos.conf.txt](https://github.com/poseidonos/poseidonos/files/9981574/pos.conf.txt)

4. I performed the "pkill -9 poseidonos" as requested before executing the ./start_poseidonos.sh script. I still get the following result:

keith@poseidonos:/etc/pos$ ps -ef| grep poseidon
avahi      934     1  0 09:02 ?        00:00:00 avahi-daemon: running [poseidonos.local]
keith     4137  3747  0 09:12 pts/1    00:00:00 grep --color=auto poseidon
keith@poseidonos:/etc/pos$ pkill -9 poseidonos
keith@poseidonos:/etc/pos$ ps -ef| grep poseidon
avahi      934     1  0 09:02 ?        00:00:00 avahi-daemon: running [poseidonos.local]
keith     4144  3747  0 09:12 pts/1    00:00:00 grep --color=auto poseidon
keith@poseidonos:/etc/pos$ cd ~/dev/ibofos/poseidonos/script/
keith@poseidonos:~/dev/ibofos/poseidonos/script$ sudo ./start_poseidonos.sh 
[sudo] password for keith: 
0000:0b:00.0 (144d a808): Already using the nvme driver
0000:1b:00.0 (1987 5013): Already using the nvme driver
0000:13:00.0 (1179 0113): Already using the nvme driver
Setting maximum # of Huge Page Size is 2/3 of Total Memory Size
0000:13:00.0 (1179 0113): nvme -> uio_pci_generic
0000:1b:00.0 (1987 5013): nvme -> uio_pci_generic
0000:0b:00.0 (144d a808): nvme -> uio_pci_generic
/home/keith/dev/ibofos/poseidonos/script
apport.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apport
Current maximum # of memory map areas per process is 65530.
Setting maximum # of memory map areas per process to 65535.
vm.max_map_count = 65535
Setup env. done!
Execute poseidonos
Error: Could not connect to the CLI server. Is PoseidonOS running? (internal error message: context deadline exceeded)
Usage:
  poseidonos-cli system info [flags]

Flags:
  -h, --help   help for info

Global Flags:
      --debug            Print response for debug.
      --fs string        Field separator for the output. (default "|")
      --ip string        Set IPv4 address to PoseidonOS for this command. (default "127.0.0.1")
      --json-req         Print request in JSON form.
      --json-res         Print response in JSON form.
      --node string      Name of the node to send this command. When both --ip and this flag are specified, this flag is applied only.
      --port string      Set the port number to PoseidonOS for this command. (default "18716")
      --timeout uint32   Timeout for this command in seconds. (Note: array unmount command has 30 minutes timeout.) (default 180)
      --unit             Display unit (B, KB, MB, ...) when displaying capacity.

./start_poseidonos.sh: line 42: 2: command not found
Wait poseidonos for 1 seconds
^C
_____________________________________________________________________

Again, many thanks for helping me in trying to resolve my issue.

**Comment by minjoon-ahn** [comment]
Thanks for your quick response. 
We added more detailed logs for initializing sequence to analyze the issue. 
Please retry at the HEAD of the main branch(3cc6e19899b1ede31889df3b6d3207d91042e87b)

**Comment by neteng1** [comment]
Okay, same result, but here are the logs. 

[pos_major.log](https://github.com/poseidonos/poseidonos/files/9993828/pos_major.log)
[pos.log](https://github.com/poseidonos/poseidonos/files/9993829/pos.log)
[syslog.txt](https://github.com/poseidonos/poseidonos/files/9993831/syslog.txt)

output of the start_poseidonos.sh script. 
----------------------------------------------------------------

keith@pos-log:~/dev/ibofos/poseidonos/script$ sudo ./start_poseidonos.sh 
0000:0b:00.0 (144d a808): Already using the nvme driver
0000:1b:00.0 (1987 5013): Already using the nvme driver
0000:13:00.0 (1179 0113): Already using the nvme driver
Setting maximum # of Huge Page Size is 2/3 of Total Memory Size
0000:13:00.0 (1179 0113): nvme -> uio_pci_generic
0000:1b:00.0 (1987 5013): nvme -> uio_pci_generic
0000:0b:00.0 (144d a808): nvme -> uio_pci_generic
/home/keith/dev/ibofos/poseidonos/script
apport.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apport
Current maximum # of memory map areas per process is 65530.
Setting maximum # of memory map areas per process to 65535.
vm.max_map_count = 65535
Setup env. done!
Execute poseidonos
Error: Could not connect to the CLI server. Is PoseidonOS running? (internal error message: context deadline exceeded)
Usage:
  poseidonos-cli system info [flags]

Flags:
  -h, --help   help for info

Global Flags:
      --debug            Print response for debug.
      --fs string        Field separator for the output. (default "|")
      --ip string        Set IPv4 address to PoseidonOS for this command. (default "127.0.0.1")
      --json-req         Print request in JSON form.
      --json-res         Print response in JSON form.
      --node string      Name of the node to send this command. When both --ip and this flag are specified, this flag is applied only.
      --port string      Set the port number to PoseidonOS for this command. (default "18716")
      --timeout uint32   Timeout for this command in seconds. (Note: array unmount command has 30 minutes timeout.) (default 180)
      --unit             Display unit (B, KB, MB, ...) when displaying capacity.

./start_poseidonos.sh: line 42: 2: command not found
Wait poseidonos for 1 seconds
Error: Could not connect to the CLI server. Is PoseidonOS running? (internal error message: context deadline exceeded)
Usage:
  poseidonos-cli system info [flags]

Flags:
  -h, --help   help for info

Global Flags:
      --debug            Print response for debug.
      --fs string        Field separator for the output. (default "|")
      --ip string        Set IPv4 address to PoseidonOS for this command. (default "127.0.0.1")
      --json-req         Print request in JSON form.
      --json-res         Print response in JSON form.
      --node string      Name of the node to send this command. When both --ip and this flag are specified, this flag is applied only.
      --port string      Set the port number to PoseidonOS for this command. (default "18716")
      --timeout uint32   Timeout for this command in seconds. (Note: array unmount command has 30 minutes timeout.) (default 180)
      --unit             Display unit (B, KB, MB, ...) when displaying capacity.

./start_poseidonos.sh: line 42: 2: command not found
Wait poseidonos for 2 seconds
-----------------------------------------------------------------

I re-ran the two commands from earler:

keith@pos-log:~/dev/ibofos/poseidonos/tool/resourceChecker$ ./make_environment_checker_so_file.sh 
keith@pos-log:~/dev/ibofos/poseidonos/tool/resourceChecker$ ./environment_check_so.py 
sh: 1: make_environment_checker_so_file.sh: not found
#1
1. OS :  Matched with host OS version
2. Kernel :  Matched with host Kernel version
3-1 number of cpu : 12
3-2 clock of cpu : 2699 MHz 
4-1 Total mem info : 32111 MB
4-2 available mem info : 9673 MB
5. number of pcie device : 3
6. Check RAID configuration
------------------------------
RAID Type      |  Support
------------------------------
RAID0          |  Available
RAID10         |  Available
RAID5          |  Available
------------------------------
Meet minimum cpu numebr
Meet minimum memory
99-custom-nvme.rules File existed

-------------------------------------------

Not sure what else I can provide. Please let me know.

Thank you again!!!

**Comment by minjoon-ahn** [comment]
After internal discussion, we will deliver a solution as soon as possible. Thanks for the valuable issue report.

**Comment by isaac-baek** [comment]
Hi @neteng1,

Thank you for your valuable reports. 👍

I'm sorry for re-guide you. Please follow below steps.
1. Please update the main branch to the latest commit(9daf766).
2. Please modify from `-O2` to `-O0` at ./Makefile(line 88)
3. Please modify from `-O3` to `-O0` at ./lib/air/src/CMakeLists.txt(line 4)
4. Please run script `sudo ./script/build_ibofos.sh`. It will do clean build by default.
5. Please run command `sudo make install` at the poseidonos root directory. It will copy mandatory files to the right place.
6. Please run script `sudo ./script/start_poseidonos.sh`.
7. Please run command `sudo pkill -11 poseidonos` if poseidonos pending under initialize sequence. It will forced kill poseidonos and log backtrace at /var/log/pos/pos_backtrace.log

Please share your results(log files in /var/log/pos). It will be very helpful to figure out this issue.
Thank you again 😊

**Comment by neteng1** [comment]
Thank you @isaac-baek. I ran through the step you outlined above. However this time, it successfully executed. 

`keith@POS-Log4:~/dev/ibosfos/poseidonos/script$ sudo ./start_poseidonos.sh 
0000:0b:00.0 (144d a808): Already using the nvme driver
0000:1b:00.0 (1987 5013): Already using the nvme driver
0000:13:00.0 (1179 0113): Already using the nvme driver
Setting maximum # of Huge Page Size is 2/3 of Total Memory Size
0000:13:00.0 (1179 0113): nvme -> uio_pci_generic
0000:1b:00.0 (1987 5013): nvme -> uio_pci_generic
0000:0b:00.0 (144d a808): nvme -> uio_pci_generic
/home/keith/dev/ibosfos/poseidonos/script
apport.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apport
Current maximum # of memory map areas per process is 65530.
Setting maximum # of memory map areas per process to 65535.
vm.max_map_count = 65535
Setup env. done!
Execute poseidonos
poseidonos is running in background...
keith@POS-Log4:~/dev/ibosfos/poseidonos/script$`

I am not sure why. I am going to see if it is repeatable and also try to get a bit further with my evaluation. 

Thank you to all who have assisted me in this matter. 

I did see an error when running the ./build_lib.sh which was:
`-- Found RE2 via CMake.
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenSSL.cmake:390 (find_package_handle_standard_args)
  cmake/ssl.cmake:66 (find_package)
  CMakeLists.txt:257 (include)


-- Configuring incomplete, errors occurred!
See also "/home/keith/dev/ibofos/poseidonos/lib/grpc/cmake/build/CMakeFiles/CMakeOutput.log".
See also "/home/keith/dev/ibofos/poseidonos/lib/grpc/cmake/build/CMakeFiles/CMakeError.log".`

I am not sure if that is something I should address. Please let me know. 
The changes in the Makefile and CMakeLists.txt files that you had me do will they cause any issue for the evaluation?

Would you still like me to post the logs?

Thank you again!

**Comment by isaac-baek** [comment]
Thank you @neteng1! I'm happy for your successful execution. 😆

I'm also not sure why but maybe there are two assumptions. First, there are some errors while build library so that when pos links with libraries, it's not working properly. This may cause poseidonos is pending under initailze routine. Second, there are some old config files which will be read poseidonos. Through `make install`, old config files gonna be updated new one.


> I did see an error when running the ./build_lib.sh

It looks like some packages not installed yet. Please run script `./script/pkgdep.sh`. It will install all package what poseidonos used.


> The changes in the Makefile and CMakeLists.txt files that you had me do will they cause any issue for the evaluation?

This changes make unoptimized code for debugging. It will cause performance degradation. If poseidonos working well, you don't need to change Makefile and CMakeLists.txt files.


> Would you still like me to post the logs?

If you encounter same issue(poseidonos is pending under initialize routine), yes please post the logs. We will analyze the logs.


Thank you again!

**Comment by neteng1** [comment]
@isaac-baek, thank you for your response. So, You are saying that I should rerun the pkgdep.sh to see if the openSSL error goes away, then rerun step 5 in your instruction post (sudo make install at the root of the poseidonos directory. Should I try to put back the values to the original in the two files you asked me to modify?

**Comment by isaac-baek** [comment]
> @isaac-baek, thank you for your response. So, You are saying that I should rerun the pkgdep.sh to see if the openSSL error goes away, then rerun step 5 in your instruction post (sudo make install at the root of the poseidonos directory. Should I try to put back the values to the original in the two files you asked me to modify?

@neteng1 , Here's new guide 😀 
1. Please rerun `pkgdep.sh`. I hope it will fix library build error.
2. Please put back the values to the original in the two files I asked you to modify.
3. Please rerun step 4 and 5. Step 4 includes libraries build and poseidonos build. Step 5 updates mandatory config and yaml files.

Then, poseidonos may work well and also you could evaluate. ☺️

**Comment by neteng1** [comment]
@isaac-baek, I did as stated above and am back to the original issue of:

----------------------------------------------------------------------- 
keith@POS-Log4:~/dev/ibosfos/poseidonos/script$ sudo ./start_poseidonos.sh 
[sudo] password for keith: 
0000:0b:00.0 (144d a808): Already using the nvme driver
0000:1b:00.0 (1987 5013): Already using the nvme driver
0000:13:00.0 (1179 0113): Already using the nvme driver
Setting maximum # of Huge Page Size is 2/3 of Total Memory Size
0000:13:00.0 (1179 0113): nvme -> uio_pci_generic
0000:1b:00.0 (1987 5013): nvme -> uio_pci_generic
0000:0b:00.0 (144d a808): nvme -> uio_pci_generic
/home/keith/dev/ibosfos/poseidonos/script
apport.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apport
Current maximum # of memory map areas per process is 65530.
Setting maximum # of memory map areas per process to 65535.
vm.max_map_count = 65535
Setup env. done!
Execute poseidonos
Error: Could not connect to the CLI server. Is PoseidonOS running? (internal error message: context deadline exceeded)
Usage:
  poseidonos-cli system info [flags]

Flags:
  -h, --help   help for info

Global Flags:
      --debug            Print response for debug.
      --fs string        Field separator for the output. (default "|")
      --ip string        Set IPv4 address to PoseidonOS for this command. (default "127.0.0.1")
      --json-req         Print request in JSON form.
      --json-res         Print response in JSON form.
      --node string      Name of the node to send this command. When both --ip and this flag are specified, this flag is applied only.
      --port string      Set the port number to PoseidonOS for this command. (default "18716")
      --timeout uint32   Timeout for this command in seconds. (Note: array unmount command has 30 minutes timeout.) (default 180)
      --unit             Display unit (B, KB, MB, ...) when displaying capacity.

./start_poseidonos.sh: line 42: 2: command not found
Wait poseidonos for 1 seconds
Error: Could not connect to the CLI server. Is PoseidonOS running? (internal error message: context deadline exceeded)
Usage:
  poseidonos-cli system info [flags]

Flags:
  -h, --help   help for info

Global Flags:
      --debug            Print response for debug.
      --fs string        Field separator for the output. (default "|")
      --ip string        Set IPv4 address to PoseidonOS for this command. (default "127.0.0.1")
      --json-req         Print request in JSON form.
      --json-res         Print response in JSON form.
      --node string      Name of the node to send this command. When both --ip and this flag are specified, this flag is applied only.
      --port string      Set the port number to PoseidonOS for this command. (default "18716")
      --timeout uint32   Timeout for this command in seconds. (Note: array unmount command has 30 minutes timeout.) (default 180)
      --unit             Display unit (B, KB, MB, ...) when displaying capacity.

./start_poseidonos.sh: line 42: 2: command not found
Wait poseidonos for 2 seconds

--------------------------------------------------------------------------------

I reran pkgdep.sh and did not see any notable errors. Here is the console output of that:

[rerun of pkgdep.sh.txt](https://github.com/poseidonos/poseidonos/files/10043641/rerun.of.pkgdep.sh.txt)

Then I ran the ./build_lib with no errors as you suspected. Here is the console output for that:

[rebuild of lib after rerun of pkgdep.sh.txt](https://github.com/poseidonos/poseidonos/files/10043654/rebuild.of.lib.after.rerun.of.pkgdep.sh.txt)

Then I changed the file back to the original values and was able to cleanly run build_ibofos.sh with the following console output:

[Run with original values.txt](https://github.com/poseidonos/poseidonos/files/10043666/Run.with.original.values.txt)


Here is the pos.log as well for your info:

[pos.log](https://github.com/poseidonos/poseidonos/files/10043669/pos.log)

I am going to try the original changes to the files from your November 16 post again and see if it runs again. 

Thank you again for all your help!

**Comment by neteng1** [comment]
@isaac-baek, I wanted to also let you know my findings on going back to the modified files as you described in the November 16 post. When I make the two modifications to the files and recompile, out of three times when the values were set to 0, the poseidonos will run, when it is set to their original 02 for Makefile and 03 for CMakeList.txt, posidenos gets stuck in initializing as I described in my earlier post today. 

What do those values actually do that would make the difference? I understand from your post earlier that performance would not be good when they are set to 0. So eventually when I look at the performance I may not want that. but I may have to do that to get to functional testing. 

Please let me know. I appreciate al the support you are providing.

**Comment by isaac-baek** [comment]
Hi @neteng1 , I checked the logs you posted and I found some build errors when you ran `build_ibofos.sh`. In the `Run with original values.txt`, **lib/opentelemetry-cpp was failed to build.**

[ 83%] Performing update step for 'opentelemetry-cpp'
[ 84%] Performing configure step for 'opentelemetry-cpp'
CMake Error at /home/keith/dev/ibosfos/poseidonos/lib/opentelemetry-cpp-prefix/src/opentelemetry-cpp-stamp/opentelemetry-cpp-configure-.cmake:16 (message):
  Command failed: 1

   'cmake' '/home/keith/dev/ibosfos/poseidonos/lib/opentelemetry-cpp' '-DBUILD_TESTING=OFF' '-DWITH_OTLP=ON' '-DWITH_ABSEIL=ON' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_INSTALL_PREFIX:PATH=/home/keith/dev/ibosfos/poseidonos/lib/opentelemetry-cpp' '-DCMAKE_INSTALL_LIBDIR=lib'

  See also

    /home/keith/dev/ibosfos/poseidonos/lib/opentelemetry-cpp-prefix/src/opentelemetry-cpp-stamp/opentelemetry-cpp-configure-*.log


CMakeFiles/opentelemetry-cpp.dir/build.make:105: recipe for target 'opentelemetry-cpp-prefix/src/opentelemetry-cpp-stamp/opentelemetry-cpp-configure' failed
make[2]: *** [opentelemetry-cpp-prefix/src/opentelemetry-cpp-stamp/opentelemetry-cpp-configure] Error 1
CMakeFiles/Makefile2:630: recipe for target 'CMakeFiles/opentelemetry-cpp.dir/all' failed
make[1]: *** [CMakeFiles/opentelemetry-cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**So that poseidonos was also failed to build cause of related error.**

Compiling [poseidonos.cpp]...
In file included from /home/keith/dev/ibosfos/poseidonos/src/trace/trace_exporter.h:37:0,
                 from poseidonos.h:43,
                 from poseidonos.cpp:33:
/home/keith/dev/ibosfos/poseidonos/src/trace/otlp_factory.h:35:10: fatal error: opentelemetry/exporters/otlp/otlp_http_exporter.h: No such file or directory
 #include "opentelemetry/exporters/otlp/otlp_http_exporter.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/keith/dev/ibosfos/poseidonos/Makefile.rules:25: recipe for target 'poseidonos.o' failed
make[2]: *** [poseidonos.o] Error 1


If poseidonos build succeeded, you can find the binary file `./bin/poseidonos`. After checking this file, you can sure to run `start_poseidonos.sh`. But I'm not sure why `build_ibofos.sh` failed... Could you post `home/keith/dev/ibosfos/poseidonos/lib/opentelemetry-cpp-prefix/src/opentelemetry-cpp-stamp/opentelemetry-cpp-configure-err.log`? It will be very helpful to fix this issue. We could cross-check with our environment. Thank you for your constant interest!!

**Comment by joshyunho** [comment]
It looks like `libssl-dev` is missing for the OpenTelemetry build. Can you install the libssl-dev package (e.g. `sudo apt install libssl-dev`) to see if it fixes your build issue? After installing libssl-dev, you would need to restart from the library building step. (e.g. `sudo ./lib/build_lib.sh`)

**Comment by isaac-baek** [comment]
There is no longer response, hence this issue is closed.

**Comment by neteng1** [comment]
Sorry, it was a holiday week in the US. I installed Libssl-dev and it corrected my problem.
