### ISSUE TITLE
Telemetry configuration assistance

### ISSUE THREAD

**Issue by neteng1** [poseidonos/poseidonos#640]
I have poseidonos and poseidonos-gui up and have the ability to see the array and volume in the GUI. I am trying to get the telemetry up between the two, as I am assuming that detail statistics for the GUI would come from that connection. I used the command "sudo ./poseidonos-cli telemetry start --ip 1.0.0.193 --port 8090", but I did not see a listener in netstat after I did that. Is there any documentation that may describe the configuration and usage of telemetry? Or any assistance would be greatly appreciated. Log attached.

[pos.log](https://github.com/poseidonos/poseidonos/files/10204461/pos.log)

**Comment by mjlee34** [comment]
Hi @neteng1, poseidonos-gui and POS telemetry use different connections. You may need POS telemetry to see the detailed statistics. 

To see the detailed statistics from POS telemetry, you need to set up PrometheusDB and Grafana first. Although we are not providing any guideline for it, we will comment how you can set up the POS telemetry very soon. 😃

**Comment by dshwpark** [comment]
Hi @neteng1. Let me introduce a guide for the usage of telemetry.

- First of all, you have to enable pos to produce telemetry data using poseidonos-cli
`
$ sudo {root_dir}/bin/poseidonos-cli telemetry start
`

- Next, run the pos-exporter(we recommand running it as background)
The pos-exporter will be located at "{root_dir}/bin/" if build process is done normally.
`
$ sudo {root_dir}/bin/pos-exporter &
`

- After the above step, 2112 port may be opened. Make sure that the 2112 port is used by pos-exporter
`
$ sudo lsof -i:2112 
# COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
# pos-expor 1011  psd    3u  IPv6 10261122      0t0  TCP *:2112 (LISTEN)
`

- If the pos-exporter is running normally, now you can check the metrics using http resqeust.
`$ curl localhost:2112/metrics
<metrics will be listed....>
`

- For the metrics to be scraped periodically and managed, you may need prometheus. Install prometheus using apt and I provide default setting for the prometheus to scrape pos's metric 
`
$ sudo apt install prometheus
`
`
# Modify the prometheus config(/etc/prometheus/prometheus.yml) as below and restart prometheus using.
# ※ change "localhost" to appropriate ip where pos-exporter is running
scrape_configs:
  - job_name: 'poseidonos'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:2112']
`
`
# For restarting prometheus
sudo systemctl restart prometheus
`

**Comment by neteng1** [comment]
Thank you @dshwpark That helped tremendously. I appear to have it working all the wey to Grafana. 

![image](https://user-images.githubusercontent.com/3988748/207764821-fb9b0c99-8872-4a90-bedc-38b27e3d36df.png)

I appreciate the assistance.
