### ISSUE TITLE
커밋이 원복되어 현재 Rocky Linux에서 빌드가 불가능합니다

### ISSUE THREAD

**Issue by hspark0582** [poseidonos/poseidonos#774]
안녕하십니까. 글루시스의 박현승입니다.

사내에서 테스트를 위해 최신 커밋을 클론 받아 Rocky 8.7에서 빌드를 시도하자 spdk 빌드 중 오류가 발생하였습니다.
원인을 찾던 도중 제가 변경하였던 `lib/spdk-22.01.1.patch` 파일의 내용이 원복된 것을 확인하였습니다. (https://github.com/poseidonos/poseidonos/commit/7d0d7f2b3cf7954125dfea93c28de7fb1bd916c1)
해당 변경 사항을 재적용해주시기를 부탁드리겠습니다.

**Comment by syeonshin** [comment]
넵. 내일까지 재적용해서 업데이트 드리겠습니다. 감사합니다..!
